-- Creado por Joel Hernández

CREATE SCHEMA leon_labs;

USE leon_labs;

/*---------------TABLAS-----------------*/

-- Tabla: HIJOS
CREATE TABLE HIJOS (
    id_hijos INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    legajo INT NOT NULL,
    nombre_hijo VARCHAR(40) NOT NULL,
    edad_hijo INT NOT NULL
);

-- Tabla: EMPLEADOS
CREATE TABLE EMPLEADOS (
    legajo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    apellido VARCHAR(40) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    domicilio VARCHAR(40) NOT NULL,
    cant_hijos INT NULL,
    vianda VARCHAR(40) NOT NULL,
    area VARCHAR(40) NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    linea_produccion INT NULL DEFAULT 0,
    antiguedad INT NOT NULL,
    sueldo DECIMAL(11 , 2 ) NOT NULL,
    fecha_ingreso DATE NOT NULL
);

-- Tabla: LINEA_PRODUCCION
CREATE TABLE LINEA_PRODUCCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    linea_produccion INT NOT NULL,
    legajo INT NOT NULL
);

-- Tabla: SERVICIOS
CREATE TABLE SERVICIOS (
    id_servicio INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo_servicio VARCHAR(40) NULL DEFAULT 'Servicio?',
    costo_servicio DECIMAL(11 , 2 ) NOT NULL,
    fecha_vencimiento DATE NOT NULL
);

-- Tabla: SERVICIOS_OP
CREATE TABLE SERVICIOS_OP (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_servicios_op INT NOT NULL,
    id_servicio INT NOT NULL
);

-- Tabla: DEPOSITO_INSUMOS
CREATE TABLE DEPOSITO_INSUMOS (
    id_insumo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo_insumo VARCHAR(40) NOT NULL,
    stock DECIMAL(11 , 2 ) NOT NULL,
    precio_unitario DECIMAL(11 , 2 ) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL
);

-- Tabla: ORDEN_INSUMO
CREATE TABLE ORDEN_INSUMO (
    id_orden_insumo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_insumo INT NOT NULL,
    cant_necesaria DECIMAL(11 , 2 ) NOT NULL
);


-- Tabla: ORDEN_PRODUCCION
CREATE TABLE ORDEN_PRODUCCION (
    id_op INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    lote VARCHAR(12) NOT NULL,
    id_orden_insumo INT NOT NULL,
    id_servicios_op INT NOT NULL,
    id_venta INT NOT NULL,
    id_envio INT NOT NULL,
    cant_supervisores INT NOT NULL,
    cant_operarios INT NOT NULL,
    cant_unidades INT NOT NULL,
    linea_produccion INT NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_pactada DATE NOT NULL
);

-- Tabla: INFO_LOTE
CREATE TABLE INFO_LOTE (
    lote VARCHAR(12) NOT NULL,
    estado_lote VARCHAR(10) NOT NULL,
    SA INT NOT NULL,
    CONSTRAINT PK_INFO_LOTE PRIMARY KEY (lote)
);

-- Tabla: VENTAS
CREATE TABLE VENTAS (
    id_venta INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    precio_venta DECIMAL(13 , 2 ) NOT NULL,
    cliente VARCHAR(40) NOT NULL
);

-- Tabla: ENVIOS
CREATE TABLE ENVIOS (
    id_envio INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pais_destino VARCHAR(40) NOT NULL,
    empresa_envio VARCHAR(40) NOT NULL,
    costo_envio DECIMAL(11 , 2 ) NOT NULL,
    fecha_entrega DATE NOT NULL
);

-- Tabla: FECHAS
CREATE TABLE FECHAS (
    fecha_pactada DATE NOT NULL,
    fecha_entrega DATE NOT NULL,
    resultado VARCHAR(10) NOT NULL,
    CONSTRAINT PK_FECHAS PRIMARY KEY (fecha_pactada)
);


/*---------------------------CLAVES FORÁNEAS----------------------------*/

-- Referencia: FK_HIJOS_EMPLEADOS (tabla: HIJOS)
ALTER TABLE HIJOS ADD CONSTRAINT FK_HIJOS_EMPLEADOS FOREIGN KEY FK_HIJOS_EMPLEADOS (legajo)
    REFERENCES EMPLEADOS (legajo);

-- Referencia: FK_LINEA_PRODUCCION_EMPLEADOS (tabla: LINEA_PRODUCCION)
ALTER TABLE LINEA_PRODUCCION ADD CONSTRAINT FK_LINEA_PRODUCCION_EMPLEADOS FOREIGN KEY FK_LINEA_PRODUCCION_EMPLEADOS (legajo)
    REFERENCES EMPLEADOS (legajo);
    
-- Referencia: FK_SERVICIOS_OP_SERVICIOS (tabla: SERVICIOS_OP)
ALTER TABLE SERVICIOS_OP ADD CONSTRAINT FK_SERVICIOS_OP_SERVICIOS FOREIGN KEY FK_SERVICIOS_OP_SERVICIOS (id_servicio)
    REFERENCES SERVICIOS (id_servicio);

-- Referencia: FK_ORDEN_INSUMOS_DEPOSITO_INSUMO (tabla: ORDEN_INSUMOS)
ALTER TABLE ORDEN_INSUMO ADD CONSTRAINT FK_ORDEN_INSUMO_DEPOSITO_INSUMOS FOREIGN KEY FK_ORDEN_INSUMO_DEPOSITO_INSUMO (id_insumo)
    REFERENCES DEPOSITO_INSUMOS (id_insumo);

-- Referencia: FK_ORDEN_PRODUCCION_INFO_LOTE (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_INFO_LOTE FOREIGN KEY FK_ORDEN_PRODUCCION_INFO_LOTE (lote)
    REFERENCES INFO_LOTE (lote);

-- Referencia: FK_ORDEN_PRODUCCION_ORDEN_INSUMO (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_ORDEN_INSUMO FOREIGN KEY FK_ORDEN_PRODUCCION_ORDEN_INSUMO (id_orden_insumo)
    REFERENCES ORDEN_INSUMO (id_orden_insumo);
    
-- Referencia: FK_ORDEN_PRODUCCION_SERVICIOS_OP (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_SERVICIOS_OP FOREIGN KEY FK_ORDEN_PRODUCCION_SERVICIOS_OP (id_servicios_op)
    REFERENCES SERVICIOS_OP (id);

-- Referencia: FK_ORDEN_PRODUCCION_VENTAS (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_VENTAS FOREIGN KEY FK_ORDEN_PRODUCCION_VENTAS (id_venta)
    REFERENCES VENTAS (id_venta);

-- Referencia: FK_ORDEN_PRODUCCION_ENVIOS (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_ENVIOS FOREIGN KEY FK_ORDEN_PRODUCCION_ENVIOS (id_envio)
    REFERENCES ENVIOS (id_envio);
    
    -- Referencia: FK_ORDEN_PRODUCCION_LINEA_PRODUCCION (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_LINEA_PRODUCCION FOREIGN KEY FK_ORDEN_PRODUCCION_LINEA_PRODUCCION (linea_produccion)
    REFERENCES LINEA_PRODUCCION (id);

-- Referencia: FK_ORDEN_PRODUCCION_FECHAS (tabla: ORDEN_PRODUCCION)
ALTER TABLE ORDEN_PRODUCCION ADD CONSTRAINT FK_ORDEN_PRODUCCION_FECHAS FOREIGN KEY FK_ORDEN_PRODUCCION_FECHAS (fecha_pactada)
    REFERENCES FECHAS (fecha_pactada);

-- End of file.
